services:
  mpi-master:
    image: distributed-graph-system:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "8000:8000"
    networks:
        - mpi-network
    volumes:
      - shared-data:/app/temp
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_MCA_btl_tcp_if_include=eth0
      - OMPI_MCA_btl=^openib
    command: >
      bash -c "
        echo \"$$(hostname -i) mpi-master\" >> /etc/hosts &&
        for i in \$$(seq 1 10); do
          if ping -c 1 mpi-worker-1 &> /dev/null; then
            echo \"All hosts resolved, starting application...\" &&
            mpirun --allow-run-as-root -np 3 
            -hostfile /app/mpi-hostfile
            /app/distributed-graph-system &&
            break
          else
            echo \"Waiting for all hosts to be available... (Attempt $$i)\" &&
            sleep 5
          fi
        done
      "

  mpi-worker:
    image: distributed-graph-system:latest
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      networks:
        - mpi-network
      volumes:
        - shared-data:/app/temp
      environment:
        - OMPI_ALLOW_RUN_AS_ROOT=1
        - OMPI_MCA_btl_tcp_if_include=eth0
        - OMPI_MCA_btl=^openib
      command: >
        bash -c "
        echo \"$$(hostname -i) $$(hostname)\" >> /etc/hosts &&
        echo \"Waiting for tasks from master...\" &&
        tail -f /dev/null
      "

networks:
  mpi-network:
    driver: overlay

volumnes:
  shared-data
