[supervisord]
nodaemon=true
user=root
loglevel=info

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/var/log/sshd.log
stderr_logfile=/var/log/sshd.err

[program:rocket-server]
command=/bin/bash -c "cd /app && cargo run --bin server"
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/app.log
stderr_logfile=/var/log/app.err
stopasgroup=true
environment=OMPI_ALLOW_RUN_AS_ROOT=1,OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1,RUST_BACKTRACE=1,RUST_LOG=debug
startretries=3